# ai_generator.py
import os
import re
from google import genai
from character import CUSTOM_CHARACTERS, AVAILABLE_CHARACTERS, rotate_point

def generate_shape_code(api_key, shape_description):
    """
    Calls the Gemini API to generate Python code for a new shape.
    """
    try:
        client = genai.Client(api_key=api_key)
        
        prompt = f"""
        You are an expert Python Tkinter programmer writing a function to draw a character.
        The user wants to draw: '{shape_description}'.
        
        Requirements:
        1. Write a SINGLE Python function named exactly 'draw_custom_character'.
        2. The function signature MUST be: def draw_custom_character(canvas, cx, cy, cell_size, direction, color_hex):
        3. You must use 'rotate_point(x, y, direction)' to rotate all coordinates. The base character (direction == "East") should face RIGHT.
        3a. IMPORTANT: DO NOT define the 'rotate_point' function yourself! It is already imported globally. Just call it.
        4. The coordinates x and y for rotate_point should be relative to the center (0,0) and typically range from -0.4 to 0.4.
        5. To get screen coordinates, use this exact formula:
           screen_x = cx + rotated_x * cell_size
           screen_y = cy + rotated_y * cell_size
        6. Draw the character using canvas.create_polygon, canvas.create_line, or canvas.create_oval.
        7. Use 'color_hex' for the main fill color, and outline width = max(2, int(cell_size * 0.06)).
        8. Return ONLY the python code block. Do NOT include markdown formatting outside the code block, but you CAN use ```python ... ``` around the code.

        Example of correct structure:
        ```python
        def draw_custom_character(canvas, cx, cy, cell_size, direction, color_hex):
            line_width = max(2, int(cell_size * 0.06))
            
            pts = [(-0.2, -0.2), (0.2, -0.2), (0.2, 0.2), (-0.2, 0.2)]
            rotated_pts = [rotate_point(x, y, direction) for x, y in pts]
            screen_pts = [coord for pt in rotated_pts for coord in (cx + pt[0]*cell_size, cy + pt[1]*cell_size)]
            
            canvas.create_polygon(screen_pts, fill=color_hex, outline="black", width=line_width)
        ```
        """
        
        response = client.models.generate_content(
            model='gemini-3.1-flash-lite',
            contents=prompt,
        )
        
        return response.text
        
    except Exception as e:
        return f"ERROR: {str(e)}"

def extract_python_code(raw_text):
    """Extracts python code from markdown code blocks if present."""
    if "```python" in raw_text:
        match = re.search(r'```python(.*?)```', raw_text, re.DOTALL)
        if match:
            return match.group(1).strip()
    elif "```" in raw_text:
        match = re.search(r'```(.*?)```', raw_text, re.DOTALL)
        if match:
            return match.group(1).strip()
    return raw_text.strip()

def save_and_load_shape(shape_name, raw_code):
    """
    Saves the generated code to a file and loads it into the game's registry.
    """
    code = extract_python_code(raw_code)
    
    # Very basic safety check for educational environment
    if "os." in code or "subprocess" in code or "import" in code:
        raise ValueError("Generated code contained unsafe imports or commands.")
        
    if "def draw_custom_character" not in code:
        raise ValueError("Generated code did not contain 'def draw_custom_character'.")
    
    # Make a safe filename
    filename = "".join(c for c in shape_name if c.isalnum() or c in " _-").strip().replace(" ", "_").lower()
    if not filename:
        filename = "custom_character"
        
    # Create directory if it doesn't exist
    if not os.path.exists("characters"):
        os.makedirs("characters")
        
    filepath = os.path.join("characters", f"{filename}.py")
    
    # Prepend the necessary import so the file is complete
    full_file_content = f"# Generated by Gemini AI\nfrom character import rotate_point\n\n{code}\n"
    
    # Save the file to the user's PC
    with open(filepath, "w") as f:
        f.write(full_file_content)
        
    # Dynamically execute the code in a restricted local scope
    local_scope = {"rotate_point": rotate_point}
    exec(code, globals(), local_scope)
    
    # Extract the function
    if "draw_custom_character" in local_scope:
        func = local_scope["draw_custom_character"]
        # Register it in our game!
        CUSTOM_CHARACTERS[shape_name] = func
        
        # Add to the dropdown list if not already there
        if shape_name not in AVAILABLE_CHARACTERS:
            # Insert it right before "Generate with AI..."
            gen_idx = AVAILABLE_CHARACTERS.index("Generate with AI...")
            AVAILABLE_CHARACTERS.insert(gen_idx, shape_name)
            
        return filepath
    else:
        raise ValueError("Could not find the function after executing code.")
