# Generated by Gemini AI
from character import rotate_point

def draw_custom_character(canvas, cx, cy, cell_size, direction, color_hex):
    line_width = max(2, int(cell_size * 0.06))
    
    # Define points for the character '2' (base: facing East)
    # The segments form a 2-shape: top curve, diagonal, and horizontal base
    # Coordinates are relative to center (0,0) within range -0.4 to 0.4
    points = [
        (-0.3, -0.2), # Start top-left
        (0.0, -0.35), # Top-mid curve
        (0.3, -0.2),  # Top-right
        (0.3, -0.05), # Right edge
        (-0.3, 0.35), # Diagonal to bottom-left
        (0.3, 0.35)   # Horizontal base
    ]
    
    # Apply rotation
    rotated_pts = [rotate_point(x, y, direction) for x, y in points]
    
    # Convert to screen coordinates
    screen_coords = []
    for rx, ry in rotated_pts:
        screen_x = cx + rx * cell_size
        screen_y = cy + ry * cell_size
        screen_coords.extend([screen_x, screen_y])
    
    # Draw using create_line since '2' is a stroke-based character
    canvas.create_line(
        screen_coords, 
        fill=color_hex, 
        width=line_width, 
        capstyle="round", 
        joinstyle="round"
    )
