# Generated by Gemini AI
from character import rotate_point

def draw_custom_character(canvas, cx, cy, cell_size, direction, color_hex):
    def rotate_point(x, y, direction):
        if direction == "East":
            return x, y
        elif direction == "South":
            return -y, x
        elif direction == "West":
            return -x, -y
        elif direction == "North":
            return y, -x
        return x, y

    line_width = max(2, int(cell_size * 0.06))
    
    # Coordinates for '2' based on center (0,0) with range roughly -0.4 to 0.4
    # Defined as a series of line segments forming the shape
    # Top curve, diagonal, and base
    points = [
        (-0.3, -0.2), (-0.2, -0.3), (0.2, -0.3), (0.3, -0.2), 
        (0.3, -0.1), (0.2, 0.0), (-0.3, 0.3), (0.3, 0.3)
    ]
    
    # Constructing as a path: Top arch -> diagonal down-left -> horizontal base
    # Segment 1: Arch
    arch_pts = [(-0.25, -0.2), (-0.1, -0.35), (0.1, -0.35), (0.25, -0.2)]
    # Segment 2: Diagonal
    diag_pts = [(0.25, -0.2), (-0.25, 0.3)]
    # Segment 3: Base
    base_pts = [(-0.3, 0.3), (0.3, 0.3)]
    
    paths = [arch_pts, diag_pts, base_pts]
    
    for path in paths:
        rotated = [rotate_point(x, y, direction) for x, y in path]
        screen_pts = []
        for rx, ry in rotated:
            screen_pts.extend([cx + rx * cell_size, cy + ry * cell_size])
        
        canvas.create_line(screen_pts, fill=color_hex, width=line_width, capstyle="round", joinstyle="round")
