# Generated by Gemini AI
from character import rotate_point

def draw_custom_character(canvas, cx, cy, cell_size, direction, color_hex):
    line_width = max(2, int(cell_size * 0.06))

    def rotate_point(x, y, direction):
        if direction == "East":
            return (x, y)
        elif direction == "South":
            return (-y, x)
        elif direction == "West":
            return (-x, -y)
        elif direction == "North":
            return (y, -x)
        return (x, y)

    # Frog body (ellipse)
    body_coords = (-0.35, -0.2, 0.35, 0.2)
    x1, y1 = rotate_point(body_coords[0], body_coords[1], direction)
    x2, y2 = rotate_point(body_coords[2], body_coords[3], direction)
    
    canvas.create_oval(cx + x1 * cell_size, cy + y1 * cell_size,
                       cx + x2 * cell_size, cy + y2 * cell_size,
                       fill=color_hex, outline="black", width=line_width)

    # Frog eyes (two circles)
    eye_offsets = [(-0.2, -0.15), (-0.2, 0.15)]
    for ox, oy in eye_offsets:
        rx, ry = rotate_point(ox, oy, direction)
        ex1, ey1 = rx - 0.08, ry - 0.08
        ex2, ey2 = rx + 0.08, ry + 0.08
        canvas.create_oval(cx + ex1 * cell_size, cy + ey1 * cell_size,
                           cx + ex2 * cell_size, cy + ey2 * cell_size,
                           fill="white", outline="black", width=line_width)
        # Pupils
        px1, py1 = rx - 0.03, ry - 0.03
        px2, py2 = rx + 0.03, ry + 0.03
        canvas.create_oval(cx + px1 * cell_size, cy + py1 * cell_size,
                           cx + px2 * cell_size, cy + py2 * cell_size,
                           fill="black")

    # Frog mouth
    mouth_pts = [(0.25, -0.1), (0.35, 0), (0.25, 0.1)]
    rot_mouth = [rotate_point(x, y, direction) for x, y in mouth_pts]
    screen_mouth = []
    for rx, ry in rot_mouth:
        screen_mouth.extend([cx + rx * cell_size, cy + ry * cell_size])
    
    canvas.create_line(screen_mouth, fill="black", width=line_width)
