# Generated by Gemini AI
from character import rotate_point

def draw_custom_character(canvas, cx, cy, cell_size, direction, color_hex):
    line_width = max(2, int(cell_size * 0.06))
    
    # Define a simple line segment centered at 0,0
    # From left to right (facing East)
    x1, y1 = -0.35, 0.0
    x2, y2 = 0.35, 0.0
    
    rx1, ry1 = rotate_point(x1, y1, direction)
    rx2, ry2 = rotate_point(x2, y2, direction)
    
    screen_x1 = cx + rx1 * cell_size
    screen_y1 = cy + ry1 * cell_size
    screen_x2 = cx + rx2 * cell_size
    screen_y2 = cy + ry2 * cell_size
    
    canvas.create_line(screen_x1, screen_y1, screen_x2, screen_y2, fill=color_hex, width=line_width * 2)
