# Generated by Gemini AI
from character import rotate_point

def draw_custom_character(canvas, cx, cy, cell_size, direction, color_hex):
    line_width = max(2, int(cell_size * 0.06))

    # Snowman design: 3 circles (base, middle, head)
    # Relative coordinates: (x, y, radius)
    circles = [
        (0.0, 0.25, 0.25),   # Base
        (0.0, -0.05, 0.18),  # Middle
        (0.0, -0.28, 0.12)   # Head
    ]

    for x_rel, y_rel, r_rel in circles:
        # Rotate center of circle
        rx, ry = rotate_point(x_rel, y_rel, direction)
        
        # Calculate screen coordinates
        screen_x = cx + rx * cell_size
        screen_y = cy + ry * cell_size
        r_screen = r_rel * cell_size
        
        canvas.create_oval(
            screen_x - r_screen, screen_y - r_screen,
            screen_x + r_screen, screen_y + r_screen,
            fill=color_hex, outline="black", width=line_width
        )

    # Eyes
    for eye_x in [-0.04, 0.04]:
        ex, ey = rotate_point(eye_x, -0.32, direction)
        canvas.create_oval(
            cx + ex * cell_size - 0.02 * cell_size, cy + ey * cell_size - 0.02 * cell_size,
            cx + ex * cell_size + 0.02 * cell_size, cy + ey * cell_size + 0.02 * cell_size,
            fill="black"
        )

    # Carrot nose
    nx1, ny1 = rotate_point(0, -0.28, direction)
    nx2, ny2 = rotate_point(0.15, -0.25, direction)
    canvas.create_line(
        cx + nx1 * cell_size, cy + ny1 * cell_size,
        cx + nx2 * cell_size, cy + ny2 * cell_size,
        fill="orange", width=line_width
    )
