# Generated by Gemini AI
from character import rotate_point

def draw_custom_character(canvas, cx, cy, cell_size, direction, color_hex):
    line_width = max(2, int(cell_size * 0.06))

    # The Stanford "Block S" consists of two vertical bars and a central curve.
    # Coordinates centered at (0,0) with scale ~0.4
    # Defined as a set of points for a polygon to represent the Block S
    pts = [
        (-0.25, -0.35), (0.25, -0.35), (0.25, -0.2), (-0.1, -0.2),
        (-0.1, -0.05), (0.25, -0.05), (0.25, 0.05), (-0.1, 0.05),
        (-0.1, 0.2), (0.25, 0.2), (0.25, 0.35), (-0.25, 0.35),
        (-0.25, 0.2), (-0.1, 0.2), (-0.1, 0.05), (-0.25, 0.05),
        (-0.25, -0.05), (-0.1, -0.05), (-0.1, -0.2), (-0.25, -0.2)
    ]

    rotated_pts = [rotate_point(x, y, direction) for x, y in pts]
    screen_pts = []
    for rx, ry in rotated_pts:
        screen_pts.append(cx + rx * cell_size)
        screen_pts.append(cy + ry * cell_size)
    
    canvas.create_polygon(screen_pts, fill=color_hex, outline="black", width=line_width)
